#!/usr/bin/env python3
import argparse
import requests
import json

f = open("ip_address.txt","r")
backend_computer_address = f.read()
f.close()

def healthcheck():
	f = open("cookie.txt","r")
	cookie = {'jwt': f.read()}
	f.close()
	url = 'https://'+backend_computer_address+':9103/interoperability/api/admin/healthcheck'
	response = requests.get(url, cookies=cookie, verify='../cert/CA/CA.pem')
	print("status code= ",response.status_code)
	if(response.status_code == 200):
		print(response.json())
		# cookies = response.cookies.get_dict()
		# f= open("cookie.txt","w+")
		# f.write(cookies['jwt'])
		# f.close
	else:
		print("Error")
		print(response.text)


parser = argparse.ArgumentParser(description= 'This would give a health check of our API')

args = parser.parse_args()

healthcheck()