#!/usr/bin/env python3
import argparse
import requests
import json
import os
from auth import auth

f = open("ip_address.txt","r")
backend_computer_address = f.read()
f.close()


def logout():
    
    
    f = open("cookie.txt","r")
    cookie = {'jwt': f.read()}
    f.close()
    
    url = 'https://'+backend_computer_address+':9103/interoperability/api/logout'
    response = requests.post(url, cookies=cookie, verify='../cert/CA/CA.pem')
    
    
    print("status code= ",response.status_code)
    if(response.status_code == 200):
        print(response.text)
        # cookies = response.cookies.get_dict()
        f= open("cookie.txt","w+")
        
        f.close
    else:
        print("Error")
        print(response.text)


parser = argparse.ArgumentParser(description= 'This would let a user logout our API accordinly')


logout()