#!/usr/bin/env python3
import argparse
import requests
import json
from helperWriter import textCsvWriter

f = open("ip_address.txt","r")
backend_computer_address = f.read()
f.close()

def passesperstation(station, datefrom, dateto, format):
    f = open("cookie.txt","r")
    cookie = {'jwt': f.read()}
    f.close()
    url = f'https://'+backend_computer_address+':9103/interoperability/api/PassesPerStation/{station}/{datefrom}/{dateto}?format={format}'
    response = requests.get(url, cookies=cookie, verify='../cert/CA/CA.pem')
    print(response.status_code)
    if(format=='csv'and response.status_code==200):
        textCsvWriter("./PassesPerStation.csv",response.text)
    elif(format == 'json' and response.status_code==200):
        print(json.dumps(response.json(), indent=5, sort_keys=False))
    else:
        print(response.text)


parser = argparse.ArgumentParser(description= 'This would return the passes of the station declared in the args and the dates accordingly')
parser.add_argument('-s','--station', required=True, help='The name of the station you are about to make a query')
parser.add_argument('-df','--datefrom', required=True, help='The date for the period starts and you want to make a query ')
parser.add_argument('-dt','--dateto', required=True, help='The date for the period ends and you want to make a query')
parser.add_argument('-f', '--format', required=True, help='The format of the responce data should have')

args = parser.parse_args()

passesperstation(args.station, args.datefrom, args.dateto, args.format)
# se2164 passesperstation -s AO01 -df 20210301 -dt 20210601 -f json
